#!/bin/sh

RCDLINKS="2,S99 0,K00"

PATH=/sbin:/bin:/usr/bin:/usr/sbin


case "$1" in
start)
    test -f /proc/pcspkr && echo "1046:100 1318:100 1568:100" >/proc/pcspkr || \
	echo "INITBEEP error: no /proc/pcspkr file. Are pcspkr.o loaded?"
    ;;
stop)
    test -f /proc/pcspkr && echo "1568:100 1318:100 1046:100" >/proc/pcspkr || \
	echo "INITBEEP error: no /proc/pcspkr file. Are pcspkr.o loaded?"
    ;;
*)
    echo "Usage: /etc/init.d/ntpdate {start|stop}"
    exit 1
esac

exit 0
