#! /bin/sh
# /etc/init.d/modules: loads the appropriate modules

# Editted for LRP -- Dave Cinege
# Optimized by Eric Wolzak

RCDLINKS="S,S20"

. /etc/modutils.conf

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

lsalias () {	for i in $@; do
		    cat /sys/bus/$i/devices/*/modalias 2>/dev/null;
		done; }

#kernel=`uname -r`
#ln -s /lib/modules /lib/modules/$kernel

# Loop over every line in /etc/modules.
echo 'Loading modules: '
depmod
grep ^[a-z0-9A-Z] /etc/modules |
while read module args
do
	modprobe $module $args 2>/dev/null
	lsmod | grep -n -q ^$module || \
	logger modutils module $module could not be loaded
done

#read /etc/modules.d
cat /etc/modules.d/* 2>/dev/null| grep ^[a-z0-9A-Z] | sed 's/\.ko//' |
while read module args
do
	modprobe $module $args 2>/dev/null
	lsmod | grep -n -q ^$module || \
	logger modutils module $module could not be loaded
done

# touch uevent for load all required modules for cold-plugged devices
find /sys -type f -name 'uevent' | while read dev_event; do
	echo 'add' > $dev_event
done
