#!/bin/sh

# 99ibod-down by Paul Martin 21 Feb 2001. You may treat this program as if
# it were in the public domain.

# 99ibod-down stops ibod when ippp0 goes down.

test -f /usr/bin/ibod || exit 0

if [ "$PPP_IFACE" = "ippp0" ]
then
   (
     start-stop-daemon --stop --quiet --exec /usr/bin/ibod
   ) \
 || true
fi
