#!/bin/sh
# Creates openssh keys J. Nilo May 2001
	ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ""
	ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
	ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
        ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
