#!/bin/sh
#
# When the ppp link comes up, this script is called with the following
# parameters
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd
#

. /etc/ppp/ppp-hsh.conf

OUTPUT=$1
if [ "$OUTPUT" = "" ]; 
then
  OUTPUT="$PPP_IFACE"
fi

if [ -f /var/run/radattr.$OUTPUT ]
then
   IP=$5
   if [ "$IP" = "" ]; 
   then
     IP="$PPP_REMOTE"
   fi

   DOWNSPEED=`$AWK  '/PPPD-Downstream-Speed-Limit/ {print $2}'  /var/run/radattr.$OUTPUT`
   UPSPEED=`$AWK  '/PPPD-Upstream-Speed-Limit/ {print $2}'  /var/run/radattr.$OUTPUT`
   FILTERS=`$AWK  '/Filter-Id/ {print $2}'  /var/run/radattr.$OUTPUT`
   [ -z "$UPSPEED" ] && UPSPEED=0
   [ -z "$DOWNSPEED" ] && DOWNSPEED=0

   if [ w${debug} = w1 ] ; then
     echo "Debug mode" >>/tmp/pptpd
     echo $DOWNSPEED >>/tmp/pptpd
     echo $UPSPEED >>/tmp/pptpd
     echo $FILTERS >>/tmp/pptpd
   fi;

#### Filters
  if [ w$FILTERS != w ] ;
  then
    FILTARR=`echo $FILTERS|sed 's/;/\n/g'`
    IXSPEED=`echo "$FILTARR"|awk '/IXSPEED/ {split($1, a, ":"); print a[2] + 0}'`
    NEGDEP=`echo "$FILTARR"|awk '/NEGDEP/ {split($1, a, ":"); print a[2]}'`
  fi

##### speed server->client
  if [ "$UPSPEED" != "0" ] ;
  then
    if [ -n "$COEF" ] ; 
    then
	UPSPEED=$(($UPSPEED*$COEF))
    fi
  else
     UPSPEED=102400
  fi
  URATE=$(($UPSPEED/2))
  $TCCR dev $OUTPUT parent 1: classid 1:1 htb rate ${UPSPEED}kbit $UBURST quantum 1514
  $TCCR dev $OUTPUT parent 1:1 classid 1:10 htb rate ${URATE}kbit ceil ${UPSPEED}kbit $UBURST prio 1 quantum 1514
  $TCCR dev $OUTPUT parent 1:1 classid 1:20 htb rate ${URATE}kbit ceil ${UPSPEED}kbit $UBURST prio 2 quantum 1514
  if [ -n "$IXSPEED" ]; then
    [ "$UPSPEED" -gt "$IXSPEED" ] && IS=$UPSPEED || IS=$IXSPEED
    $TCCR dev $OUTPUT parent 1: classid 1:2 htb rate ${IS}kbit $UBURST prio 2 quantum 1514
  fi

##### speed client->server
  if [ "$DOWNSPEED" != "0" ] ;
  then
    if [ -n "$COEF" ] ; 
    then
      DOWNSPEED=$(($DOWNSPEED*$COEF))
    fi
  else
     DOWNSPEED=102400
  fi
  $TCQD dev $OUTPUT handle ffff: ingress
  $TCQR dev $OUTPUT handle ffff: ingress
  /usr/sbin/hsh.sh set $IP $DOWNSPEED
  if [ -z "$IXSPEED" ]; then
    $TCFR dev $OUTPUT parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev $IDEV
  else
    [ "$DOWNSPEED" -gt "$IXSPEED" ] && IS=$DOWNSPEED || IS=$IXSPEED
    [ -n "$IXDEV" ] && /usr/sbin/hsh.sh set $IP $IXSPEED $IXDEV
  fi

fi

