#!/bin/sh
#
# When the ppp link comes up, this script is called with the following
# parameters
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd
#

. /etc/ppp/ppp-hsh.conf

OUTPUT=$1
if [ "$OUTPUT" = "" ];
then
  OUTPUT="$PPP_IFACE"
fi
  

if [ -f /var/run/radattr.$OUTPUT ]
then
   IP=$5
   if [ "$IP" = "" ];
      then
      IP="$PPP_REMOTE"
   fi	         

   $TC qdisc del dev $OUTPUT root    2>/dev/null
   $TC qdisc del dev $OUTPUT ingress 2>/dev/null
   /usr/sbin/hsh.sh $IP 102400

 fi

