#!/bin/sh
# Save daily LOGDEPTH versions of logfile 
LOGDEPTH=4
# Space separated list of logfiles
LOGFILE="/var/log/shorewall.log"

for log in $LOGFILE ; do
    if [ -f $log ]; then
	savelog -g wheel -m 640 -u root -c $LOGDEPTH $log >/dev/null
    fi
done
/etc/init.d/ulogd reload
