#!/bin/sh
#

RCDLINKS="2,S60 3,S60 6,K60"

error () {
	echo "ez-ipupd error: $1"
	exit 1
}

DAEMON=/usr/bin/ez-ipupdate
VARRUN=/var/run/ez-ipupd.pid

getconfig() { # 0: no daemon / 1: daemon
	local CONF NAME LIST=""
	for CONF in /etc/ez-ipupdate/*.conf; do
		if [ -f "${CONF}" ]; then
			# Don't run configurations that are (not) daemons
			grep -q '^[[:space:]]*daemon' "${CONF}"; [ $? -eq $1 ] && continue
			# Don't run configurations that run in the foreground
			grep -q '^[[:space:]]*foreground' "${CONF}" && continue
			# add config to list
			NAME="${CONF##*/}"
			LIST="${LIST} ${NAME%.*}"
		fi
	done
	echo ${LIST}
}

start() {
	local NAME LIST=$(getconfig 1)

	if [ -z "${LIST}" ]; then
		echo "Error: You need at least one config file in /etc/ez-ipupdate"
		echo "containing the 'daemon' keyword and no 'foreground' keyword."
		return 1
	fi

	if [ ! -d /var/run/ez-ipupdate ]; then
		mkdir -p /var/run/ez-ipupdate
	fi

	for NAME in ${LIST}; do
		local CONFIG="/etc/ez-ipupdate/${NAME}.conf"
		local PIDFILE="/var/run/ez-ipupdate/${NAME}.pid"
		echo "Starting ez-ipupdate (${NAME})..."
		start-stop-daemon -p "${PIDFILE}" --start --quiet --exec ${DAEMON} \
			-- -c "${CONFIG}" -F "${PIDFILE}"
	done
	return 0  # do not fail
}

stop() {
	local PIDFILE NAME
	for PIDFILE in /var/run/ez-ipupdate/*.pid; do
		if [ -f "${PIDFILE}" ]; then
			NAME="${PIDFILE##*/}"
			echo "Stopping ez-ipupdate (${NAME%.*})"
			start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PIDFILE}"
		else
			echo "Error: No running ez-ipupdate process"
		fi
	done
	return 0  # do not fail
}


case "$1" in
	start)
		echo "Starting $DAEMON..."
		start
	;;
	stop)
		stop
	;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
	;;
	*)
	echo "Usage: $0 {start|stop|restart|force-reload}"
	exit 1
	;;
esac
exit 0
