--- Makefile.OLD	2011-11-18 23:53:31.000000000 +0200
+++ Makefile	2011-11-19 00:09:09.236641104 +0200
@@ -3,17 +3,16 @@
 OBJS			= input.o menurt.o listbox.o winops.o labels.o \
 				msgboxes.o
 
+RANLIB ?= ranlib
+
 all: libtextbox.a
 
 libtextbox.a: $(OBJS)
 	rm -rf libtextbox.a
-	ar cq libtextbox.a $(OBJS)
-	ranlib libtextbox.a
+	$(AR) cq libtextbox.a $(OBJS)
+	$(RANLIB) libtextbox.a
 #	gcc -shared -o libtextbox.so $(OBJS)
 
-%.o: %.c *.h
-	gcc -O2 -g -Wall -fPIC $(INCLUDEDIR) -c -o $*.o $<
-
 clean:
 	rm -rf *.o *~ libtextbox.a libtextbox.so
 
