#! /bin/sh
#
# urandom	This script saves the random seed between reboots.
#		It is called from the boot, halt and reboot scripts.
#
RCDLINKS="S,S55 0,S30"


[ -c /dev/urandom ] || exit 0

SAVEDFILE=/var/lib/random-seed
POOLSIZE=512
[ -f /proc/sys/kernel/random/poolsize ] && POOLSIZE="$(cat /proc/sys/kernel/random/poolsize)"

case "$1" in
	start|"")
		echo -n "Initializing random number generator... "
		# Load and then save POOLSIZE bytes,
		# which is the size of the entropy pool
		if [ -f "$SAVEDFILE" ]
		then
		    cat "$SAVEDFILE" >/dev/urandom
		fi
		rm -f $SAVEDFILE
		umask 077
		dd if=/dev/urandom of=$SAVEDFILE bs=$POOLSIZE count=1 >/dev/null 2>&1 \
		|| echo "urandom start: failed."
		umask 022
		echo "done."
		;;
	stop)
		# Carry a random seed from shut-down to start-up;
		# see documentation in linux/drivers/char/random.c
		echo -n "Saving random seed... "
		umask 077
		dd if=/dev/urandom of=$SAVEDFILE bs=$POOLSIZE count=1 >/dev/null 2>&1 \
		|| echo "urandom stop: failed."	
		echo "done."
		;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac
