#!/bin/sh
# Save daily LOGDEPTH versions of syslogfile
LOGDEPTH=4
# Config file
config=/etc/mini_httpd.conf
# syslogfile name
logfile=/var/log/mini_httpd.log
# User
user=sh-httpd

[ -f $config ] && . $config

if [ -f $logfile ]; then
    savelog -u $user -g wheel -m 640 -p -c $LOGDEPTH $logfile >/dev/null
    /etc/init.d/mini_httpd reload >/dev/null
fi
