#!/bin/sh

. /etc/dhcfind.conf

PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ -f $LOCK ]; then
	echo "Lockfile is present, $0 is running?"
	exit 1
fi

touch $LOCK

ifaces=`ip a|awk "/$IFACEEXP/"'{ sub(/:/,"",$2); split($2,a,"@"); print a[1]}'|sort|uniq`

for i in $ifaces; do
	dhcp=`dhcdrop -t -i $i`
	if [ $? = 200 ]; then
		srvs=`echo "$dhcp"|sed 's/,//g'|awk '/YIP/ {print "ip=" $3 "&mac=" $8}'`
		for j in $srvs; do
			wget "$URL?iface=$i&$j" -O /tmp/$i.res
		done
		res=`cat /tmp/$i.res`
		if [ "$res" = 1 ]; then
			if [ "$AGGR" = 1  ]; then	#aggressive mode
				echo "Unimplemented";
			else
				dhcdrop -i $i -y
			fi
		fi
	fi
done

rm -f $LOCK
