#! /bin/sh
# Script to return kernel version (C) 2012 Yves Blusseau
# based on linux/scripts/patch-kernel script
#
#   usage: get-kernel-version sourcedir

PNAME=get-kernel-version

# Set directory from argument
sourcedir="${1}"

if [ "$1" = -h -o "$1" = --help -o ! -r "$sourcedir/Makefile" ]; then
cat << USAGE
usage: $PNAME [-h] sourcedir
USAGE
exit 1
fi

# return current VERSION, PATCHLEVEL, SUBLEVEL, EXTRAVERSION
TMPFILE=`mktemp --tmpdir linuxver.XXXXXX` || { echo "cannot make temp file" ; exit 1; }
grep -E "^(VERSION|PATCHLEVEL|SUBLEVEL|EXTRAVERSION)" "$sourcedir/Makefile" | \
	tr -d [:blank:] > $TMPFILE
. $TMPFILE
rm -f $TMPFILE
if [ -z "$VERSION" -o -z "$PATCHLEVEL" -o -z "$SUBLEVEL" ]; then
    echo "unable to determine kernel version from $sourcedir" >&2
    exit 1
else
    echo "$VERSION.$PATCHLEVEL.$SUBLEVEL${EXTRAVERSION}"
fi
